import AwesoMuxCore
import Foundation
import Testing

@testable import awesoMux

/// What these can and cannot see:
///
/// `Resources/Localizable.xcstrings` is not a declared SwiftPM resource, so
/// under `swift test` `String(localized:)` always falls back to formatting the
/// *source literal*. That makes these assertions a check on the source — that
/// every branch substitutes the file name, and that the *source* interpolations
/// appear in the right order — and **not** a check that the catalog agrees. An
/// earlier version of this suite claimed the latter; a `%arg` assertion on a
/// rendered string cannot fail here, because the marker only ever exists in a
/// catalog this build never loads. Nothing here can see a catalog entry whose
/// positional arguments are transposed.
///
/// `DocumentRejectionCopyCatalogTests` below covers the half this cannot, by
/// reading the catalog file the shipped `.app` actually loads.
@Suite("Document rejection copy")
struct DocumentRejectionCopyTests {
    private let pane = DocumentPane(
        fileURL: URL(fileURLWithPath: "/tmp/quarterly-plan.md"),
        title: "quarterly-plan.md")

    @Test(
        "every rejection reason renders without leaking a placeholder marker",
        arguments: [
            DocumentURLValidator.Rejection.notFileURL,
            .badExtension,
            .tooLarge,
            .unreadable,
        ])
    func rejectionCopyLeaksNoPlaceholders(reason: DocumentURLValidator.Rejection) {
        let message = DocumentPaneView.rejectionMessage(for: reason, pane: pane)

        #expect(!message.isEmpty)
        // These catch a printf specifier hand-written into a *source* literal,
        // which is the only way one could reach a user here. They cannot catch
        // a catalog problem — see the suite comment. Kept rather than deleted
        // with the `%arg` assertions because that distinction is real: `%arg`
        // is generated by `xcstringstool` and exists only in the catalog, so no
        // source edit can introduce it.
        #expect(!message.contains("%@"), "unsubstituted specifier reached the user: \(message)")
        #expect(!message.contains("%lld"), "unsubstituted specifier reached the user: \(message)")
        #expect(
            message.contains(pane.title),
            "the message should name the file it is about: \(message)")
    }

    /// The cap must come from the validator rather than a hand-typed number,
    /// or the copy drifts from the number actually enforced the next time it
    /// moves. (`.badExtension` and `readErrorMessage` carry two substitutions
    /// too — this one is not special in that respect, and none of them can see
    /// a *catalog* entry with transposed arguments.)
    @Test("the size rejection states the actual cap")
    func sizeRejectionStatesTheCap() {
        let message = DocumentPaneView.rejectionMessage(for: .tooLarge, pane: pane)
        let cap = DocumentURLValidator.maxFileSizeMegabytes

        #expect(message.contains("\(cap) MB"), "expected the cap in megabytes: \(message)")
        #expect(message.contains(pane.title))
    }

    /// The extension list is interpolated from `allowedExtensions` rather than
    /// spelled out, so adding a supported type cannot leave the copy behind.
    @Test("the extension rejection lists the supported extensions")
    func extensionRejectionListsExtensions() {
        let message = DocumentPaneView.rejectionMessage(for: .badExtension, pane: pane)

        for ext in DocumentURLValidator.allowedExtensions {
            #expect(message.contains(ext), "expected \(ext) in: \(message)")
        }
    }

    /// `.readError` frames a reason produced by `DocumentLoader`. Both halves
    /// are localized, and the risk is that they drift — a localized frame
    /// wrapping an English payload reads worse than leaving both alone.
    @Test("a read failure names the file and carries the reason through intact")
    func readErrorCarriesTheReason() {
        let reason = DocumentLoader.LoadResult.readError("REASON-SENTINEL")
        guard case let .readError(text) = reason else {
            Issue.record("the case constructed one line above must match")
            return
        }
        let message = DocumentPaneView.readErrorMessage(text, pane: pane)

        #expect(message.contains(pane.title), "should name the file: \(message)")
        #expect(message.contains("REASON-SENTINEL"), "should carry the reason: \(message)")
    }

    /// The reasons `DocumentLoader` actually produces must themselves resolve
    /// to something — a reason left empty would frame the file name with a
    /// trailing colon and nothing after it.
    @Test("the loader's own read-failure reasons render as text")
    func loaderReasonsRender() throws {
        let url = URL(fileURLWithPath: "/tmp/awesomux-not-utf8.md")
        try Data([0xFF]).write(to: url)
        defer { try? FileManager.default.removeItem(at: url) }

        guard case let .readError(reason) = DocumentLoader.load(url) else {
            Issue.record("expected a read error for non-UTF-8 content")
            return
        }
        #expect(!reason.isEmpty)
    }
}

/// The half the suite above structurally cannot reach: that the source literals
/// it renders actually have matching keys in the catalog the shipped app loads.
/// A literal with no key is not a crash — `String(localized:)` falls through to
/// the literal — so every locale silently gets English and nothing else in the
/// app notices.
@Suite("Document rejection copy catalog coverage")
struct DocumentRejectionCopyCatalogTests {

    /// Filtered out of the file rather than swept whole: `DocumentPaneView` is
    /// ~1850 lines and localizes far more than rejection copy — a file-wide
    /// sweep captures 41 literals, five of which have no catalog key today
    /// (agent-send copy, untouched by this change). That is the known drift in
    /// #198, not something this can fix, so the filter keeps the assertion
    /// honest instead of disabling it.
    ///
    /// A hardcoded list of the five expected keys was also written and then
    /// deleted: this test already asserts `count == 5` *and* `keys.contains`
    /// for every literal it finds, so the list could not fail for any reason
    /// this one would not — except when a rejection string and its catalog key
    /// are BOTH updated correctly, where it would fail spuriously. An
    /// assertion whose only distinct behaviour is breaking on correct changes
    /// is the mirror image of the vacuity this suite exists to remove.
    @Test func everyRejectionLiteralIsCovered() throws {
        let literals = try AwesoMuxStringCatalog.localizedLiterals(
            in: "Sources/awesoMux/Views/DocumentPaneView.swift")
        let rejectionLiterals = literals.filter {
            $0.hasPrefix("Can't open ") || $0.hasPrefix("Couldn't read ")
        }

        #expect(rejectionLiterals.count == 5, "found \(rejectionLiterals.count): \(rejectionLiterals)")

        let keys = try AwesoMuxStringCatalog.keys()
        for literal in rejectionLiterals {
            #expect(keys.contains(literal), "source localizes \"\(literal)\" with no catalog key")
        }
    }
}
