import test from "node:test";
import assert from "node:assert/strict";

import { formatFailure, validatePullRequest } from "../validate-pr-body.mjs";

const fullBody = `## Why
Make review safer.

## What's Included
- Add a trusted workflow.

## UI / UX
Not applicable because there is no visible change.

## Validation
- [x] \`node --test\` passed

## AI Assistance
- Assistance level: moderate

## Risk Notes
Workflow permissions were reviewed.

## Follow-ups
None.
`;

test("accepts a complete full template", () => {
  assert.equal(validatePullRequest({ body: fullBody, files: ["Sources/App.swift"] }).valid, true);
});

test("reports missing full-template sections", () => {
  const result = validatePullRequest({ body: "## Why\nBecause.\n", files: ["Sources/App.swift"] });
  assert.equal(result.valid, false);
  assert(result.errors.some((error) => error.includes("What's Included")));
});

test("accepts the lighter docs-only template", () => {
  const body = `## Why
Clarify setup.
## What's Included
- Update the guide.
## Validation
- [x] Proofread and checked local links.
## AI Assistance
- Assistance level: none
## Follow-ups
None.
`;
  assert.equal(validatePullRequest({ body, files: ["docs/setup.md"] }).valid, true);
});

test("rejects leftover placeholder comments", () => {
  const result = validatePullRequest({
    body: fullBody.replace("Make review safer.", "<!-- explain why -->"),
    files: ["Sources/App.swift"],
  });
  assert.equal(result.valid, false);
  assert(result.errors.some((error) => error.includes("placeholder")));
});

test("accepts Codesmith managed comments", () => {
  const codesmithFooter = `<!-- codesmith:footer -->
Managed footer content.
<!-- codesmith:autofix:disabled -->
<!-- /codesmith:footer -->`;
  const body = `${fullBody}\n${codesmithFooter}`;
  const result = validatePullRequest({
    body,
    files: ["Sources/App.swift"],
  });
  assert.equal(result.valid, true);
  assert.equal(body, `${fullBody}\n${codesmithFooter}`);
});

test("accepts CodeRabbit managed comments", () => {
  const codeRabbitSummary = `<!-- This is an auto-generated comment: release notes by coderabbit.ai -->
## Summary by CodeRabbit

- Hardened public seed validation.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->`;
  const result = validatePullRequest({
    body: `${fullBody}\n${codeRabbitSummary}`,
    files: ["Sources/App.swift"],
  });
  assert.equal(result.valid, true);
});

test("accepts unrelated HTML comments", () => {
  const result = validatePullRequest({
    body: `${fullBody}\n<!-- reviewer context: generated by an integration -->`,
    files: ["Sources/App.swift"],
  });
  assert.equal(result.valid, true);
});

test("rejects an actual template instruction", () => {
  const result = validatePullRequest({
    body: fullBody.replace(
      "Make review safer.",
      "<!-- What changed, and why should this change exist? Lead with the reviewer-facing outcome. -->",
    ),
    files: ["Sources/App.swift"],
  });
  assert.equal(result.valid, false);
  assert(result.errors.some((error) => error.includes("placeholder")));
});

test("does not use the Codesmith footer to fill a required section", () => {
  const codesmithFooter = `<!-- codesmith:footer -->
Managed footer content.
<!-- codesmith:autofix:enabled -->
<!-- /codesmith:footer -->`;
  const body = fullBody.replace("## Follow-ups\nNone.", "## Follow-ups\n") + codesmithFooter;
  const result = validatePullRequest({
    body,
    files: ["Sources/App.swift"],
  });
  assert.equal(result.valid, false);
  assert(result.errors.some((error) => error.includes("Follow-ups")));
});

test("accepts a manually reviewed UI section without automated evidence parsing", () => {
  assert.equal(
    validatePullRequest({
      body: fullBody.replace("Not applicable because there is no visible change.", "Updated the sidebar."),
      files: ["Sources/awesoMux/Views/Sidebar.swift"],
    }).valid,
    true,
  );
});

test("accepts validation that was not run with a reason", () => {
  const body = fullBody.replace(
    "- [x] `node --test` passed",
    "Not run because this only changes workflow metadata.",
  );
  assert.equal(validatePullRequest({ body, files: [".github/workflows/check.yml"] }).valid, true);
});

test("formats one managed marker comment", () => {
  const message = formatFailure(["Add the `Why` section."]);
  assert.match(message, /^<!-- awesomux-pr-template-validation -->/);
  assert.match(message, /Add the `Why` section\./);
});
